"""
TTS Synthesizer Wrapper using edge-tts
"""
import os
import io
import torch
import asyncio
import struct
import numpy as np
import soundfile as sf
from pocket_tts import TTSModel
import tempfile
import scipy.io.wavfile

LANGUAGE = "en"

class VoiceSynthesizer:
    def __init__(self):
        print("[TTS] Initializing pocket-tts synthesizer...")
        # A good default English voice
        # self.voice = os.getenv("TTS_VOICE", "alba")
        self.voice = "momo.safetensors"
        self.model = TTSModel.load_model()
        self.voice_state = self.model.get_state_for_audio_prompt(self.voice)
        self.sample_rate = self.model.sample_rate

    def _get_streaming_wav_header(self) -> bytes:
        """
        Creates a WAV header for streaming.
        Uses 0xFFFFFFFF for sizes since the final length is unknown.
        """
        channels = 1
        sample_width = 2  # 16-bit PCM
        
        header = b'RIFF'
        header += struct.pack('<I', 0xFFFFFFFF)  # Unknown file size
        header += b'WAVEfmt '
        header += struct.pack('<I', 16)          # Subchunk1Size (16 for PCM)
        header += struct.pack('<H', 1)           # AudioFormat (1 = PCM)
        header += struct.pack('<H', channels)    # NumChannels
        header += struct.pack('<I', self.sample_rate) # SampleRate
        header += struct.pack('<I', self.sample_rate * channels * sample_width) # ByteRate
        header += struct.pack('<H', channels * sample_width) # BlockAlign
        header += struct.pack('<H', sample_width * 8)        # BitsPerSample
        header += b'data'
        header += struct.pack('<I', 0xFFFFFFFF)  # Unknown data size
        return header

    def synthesize_stream(self, text: str):
        """
        A generator that yields WAV bytes chunk-by-chunk in real-time.
        """
        # 1. Yield the WAV header first so the client knows how to decode the stream
        yield self._get_streaming_wav_header()

        # 2. Iterate through the stream generated by pocket-tts
        generator = self.model.generate_audio_stream(self.voice_state, text, copy_state=True)
        
        for chunk in generator:
            # Pocket-tts yields float tensors. Convert them to 16-bit PCM numpy arrays.
            audio_np = chunk.detach().cpu().numpy()
            audio_int16 = (audio_np * 32767.0).astype(np.int16)
            
            # 3. Yield the raw bytes of this chunk
            yield audio_int16.tobytes()